<a href="https://colab.research.google.com/github/felipevergalr/calculo-numerico/blob/main/atividade_05_10_codigos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Atividade 05/10

Felipe Pereira Vergal Rostirola - 185210

#Parte 3.
**Exercício 4.**

In [11]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

A_g = np.array([[2.,1.,-1.],[-3.,-1.,2.],[-2.,1.,2.]])
b_g = np.array([8.,-11.,-3.])
M_g = np.column_stack((A_g,b_g))
print("Inicial:\n",M_g)

def substituicao_regressiva(U, c):
    """Resolve Ux=c, onde U é triangular superior."""
    U = np.asarray(U, dtype=float)
    c = np.asarray(c, dtype=float)
    n = len(c)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        if abs(U[i,i]) < 1e-14:
            raise np.linalg.LinAlgError("Pivô nulo na substituição regressiva")
        x[i] = (c[i] - U[i,i+1:] @ x[i+1:]) / U[i,i]
    return x

def eliminacao_gauss_sem_pivoteamento(A, b):
    """Eliminação de Gauss didática; requer pivôs não nulos."""
    M = np.column_stack((A, b)).astype(float)
    U = M[:, :-1]
    c = M[:, -1]
    n = len(c)
    for k in range(n-1):
        if abs(U[k,k]) < 1e-14:
            raise np.linalg.LinAlgError("Pivô zero: é necessária uma troca de linhas")
        for i in range(k+1,n):
            fator = U[i,k]/U[k,k]
            U[i,k:] -= fator*U[k,k:]
            c[i] -= fator*c[k]
    return substituicao_regressiva(U,c), U, c

x0, U0, c0 = eliminacao_gauss_sem_pivoteamento(A_g,b_g)
print("U =\n",U0)
print("c transformado =",c0)
print("x =",x0)

Inicial:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]
U =
 [[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]
c transformado = [8. 1. 1.]
x = [ 2.  3. -1.]


#Parte 4.

**b)**


In [ ]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

A_g = np.array([
    [ 4., -1.,  0.],
    [-1.,  4., -1.],
    [ 0., -1.,  3.]
])
b_g = np.array([15., 10., 10.])
M_g = np.column_stack((A_g,b_g))
print("Inicial:\n",M_g)

def substituicao_regressiva(U, c):
    U = np.asarray(U, dtype=float)
    c = np.asarray(c, dtype=float)
    n = len(c)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        if abs(U[i,i]) < 1e-14:
            raise np.linalg.LinAlgError("Pivô nulo na substituição regressiva")
        x[i] = (c[i] - U[i,i+1:] @ x[i+1:]) / U[i,i]
    return x

def eliminacao_gauss_sem_pivoteamento(A, b):
    M = np.column_stack((A, b)).astype(float)
    U = M[:, :-1]
    c = M[:, -1]
    n = len(c)
    for k in range(n-1):
        if abs(U[k,k]) < 1e-14:
            raise np.linalg.LinAlgError("Pivô zero: é necessária uma troca de linhas")
        for i in range(k+1,n):
            fator = U[i,k]/U[k,k]
            U[i,k:] -= fator*U[k,k:]
            c[i] -= fator*c[k]
    return substituicao_regressiva(U,c), U, c

x0, U0, c0 = eliminacao_gauss_sem_pivoteamento(A_g,b_g)
print("U =\n",U0)
print("c transformado =",c0)
print("T1, T2, T3 =",x0)

Matriz A:
 [[ 4. -1.  0.]
 [-1.  4. -1.]
 [ 0. -1.  3.]]
Vetor b: [100. 100.  50.]
